services:
  web:
    build: .
    restart: always
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

  pg:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pg

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    # volumes:
    #   - redis-data:/data

# volumes:
#   pgdata:
#   pgadmin-data:
#   redis-data:
